version: "3.9"
services:
  users_postgres_db:
    container_name: users_db_container
    hostname: users_db
    image: postgres:14.8-alpine3.18
    command:
      - "postgres"
      - "-c"
      - "max_connections=50"
      - "-c"
      - "shared_buffers=1GB"
      - "-c"
      - "effective_cache_size=4GB"
      - "-c"
      - "work_mem=16MB"
      - "-c"
      - "maintenance_work_mem=512MB"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "temp_file_limit=10GB"
      - "-c"
      - "log_min_duration_statement=200ms"
      - "-c"
      - "idle_in_transaction_session_timeout=10s"
      - "-c"
      - "lock_timeout=1s"
      - "-c"
      - "statement_timeout=60s"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
      - "-c"
      - "pg_stat_statements.max=10000"
      - "-c"
      - "pg_stat_statements.track=all"
    environment:
      POSTGRES_DB: "users-db"
      POSTGRES_USER: "dev"
      POSTGRES_PASSWORD: "dev123"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./docker-db/init:/docker-entrypoint-initdb.d
      - ./docker-db/data/db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U dev -d users-db" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    networks:
      - users_postgres

  pgadmin:
    hostname: users_admin_console
    container_name: pgadmin_container
    image: dpage/pgadmin4:7.2
    depends_on:
      - users_postgres_db
    environment:
      PGADMIN_DEFAULT_EMAIL: "dev@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "dev123"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - ./docker-db/data/pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    networks:
      - users_postgres

networks:
  users_postgres:
    driver: bridge
